source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.8.2"
gem "jekyll-seo-tag"
gem "jekyll-relative-links"
gem "webrick"

# GitHub Pages
group :jekyll_plugins do
  gem "jekyll-remote-theme"
end
